### ISSUE TITLE
No explicit license include in project

### ISSUE THREAD

**Issue by mikedg1** [frankhale/electron-inject-jquery-webview-example#3]
Since this seems to be the most well known, working example of injecting jquery usage to interact with a third party website, it would be great if you included an explicit license here. 
https://creativecommons.org/licenses/by-sa/3.0/ appears to be the default license for StackOverflow posted content, and I thought I stumbled across this on StackOverflow originally, so it would make sense to use the same license here.

Thanks

**Comment by frankhale** [comment]
Thanks for reporting this. I've added a license via commit 4614ef1ddb7ee966a185bc1cc65ff57a58756891

GNU GPL v3
